# Generated by Django 4.0.1 on 2022-01-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sell_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
