# Generated by Django 4.0.1 on 2022-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_mg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
