# Generated by Django 4.0.1 on 2022-01-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_mg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ml',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
