# Generated by Django 4.0.1 on 2022-01-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
