# Generated by Django 4.0.1 on 2022-01-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gm',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ml',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
