# Generated by Django 4.0.1 on 2022-01-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_gm_product_amount_remove_product_mg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='creation_date',
            new_name='sell_date',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='price',
        ),
        migrations.AlterField(
            model_name='sell',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
    ]
