# Generated by Django 4.0.1 on 2022-01-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_creation_date_sell_sell_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='category',
            field=models.CharField(choices=[('Cream', 'Cream'), ('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
