# Generated by Django 4.0.1 on 2022-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_sell_category_sell_price_sell_sell_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='sell_amount',
            new_name='sell_quantity',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
