# Generated by Django 4.0.1 on 2022-01-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_sell_amount_sell_sell_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='name',
            new_name='namess',
        ),
    ]
