# Generated by Django 4.0.1 on 2022-01-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_name_sell_namess'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='category',
            field=models.CharField(choices=[('Cream', 'Cream'), ('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
