# Generated by Django 4.0.1 on 2022-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_sell_category_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_quantity',
            field=models.IntegerField(blank=True, max_length=6),
        ),
    ]
