# Generated by Django 4.0.1 on 2022-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_sell_sell_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
