# Generated by Django 4.0.1 on 2022-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_sell_sell_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='namess',
            field=models.CharField(max_length=100),
        ),
    ]
