# Generated by Django 4.0.1 on 2022-01-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_sell_namess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='price',
            new_name='sell_price',
        ),
    ]
