# Generated by Django 4.0.1 on 2022-01-12 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_price_sell_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='sell_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='namess',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
