# Generated by Django 4.0.1 on 2022-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_sell_category_remove_sell_namess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='sell_cat',
            field=models.CharField(blank=True, choices=[('Cream', 'Cream'), ('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Cream', 'Cream'), ('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection')], max_length=100, null=True),
        ),
    ]
