# Generated by Django 4.0.1 on 2022-01-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complt']},
        ),
    ]
